version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "==== INSTALL PHASE ===="
      - echo "Verifying Python and Docker versions..."
      - python --version
      - pip --version
      - docker --version

  pre_build:
    commands:
      - echo "==== PRE-BUILD PHASE ===="
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Logging in to Docker registry..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

  build:
    commands:
      - echo "==== BUILD PHASE ===="
      - IMAGE_NAME="$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
      - echo "Building Docker image: $IMAGE_NAME"
      - docker build -t "$IMAGE_NAME" .
      - echo "Pushing Docker image to registry..."
      - docker push "$IMAGE_NAME"

  post_build:
    commands:
      - echo "==== POST-BUILD PHASE ===="
      - echo "Build and push completed successfully!"
      - echo "Image pushed: $IMAGE_NAME"

artifacts:
  files:
    - '**/*'
  base-directory: .

